# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash-screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, Form):
        Form.setObjectName("BOBOTIN")
        Form.resize(1200, 800)
        Form.setMinimumSize(QtCore.QSize(1200, 800))
        Form.setMaximumSize(QtCore.QSize(1200, 800))
        Form.setStyleSheet("background-image: url(view/assets/splash.png);\n"
"QProgressBar::chuck {\n"
"    border-radius: 16px;\n"
"}")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(440, 630, 331, 31))
        self.progressBar.setStyleSheet("background-color: #3B3B98;\n"
"color: #ffffff;\n"
"border-radius: 16px;\n"
"text-align: center;\n"
"font-size: 16px;")
        self.progressBar.setProperty("value", 25)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("BOBOTIN", "BOBOTIN"))
